apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-iam-js-example
  labels:
    application: aws-iam-js-example
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      application: aws-iam-js-example
  template:
    metadata:
      labels:
        application: aws-iam-js-example
        version: latest
    spec:
      containers:
      - name: aws-iam-js-example
        image: mikkeloscar/kube-aws-iam-controller-js-example:latest
        imagePullPolicy: Always
        env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
        # must be set for the AWS SDK/AWS CLI to find the credentials file.
        - name: AWS_SHARED_CREDENTIALS_FILE # used by js SDK
          value: /meta/aws-iam/credentials.process
        - name: AWS_CONFIG_FILE # must be the same value as for `AWS_SHARED_CREDENTIALS_FILE`
          value: /meta/aws-iam/credentials.process
        - name: AWS_REGION
          value: eu-central-1
        volumeMounts:
        - name: aws-iam-credentials
          mountPath: /meta/aws-iam
          readOnly: true
        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
      volumes:
      - name: aws-iam-credentials
        secret:
          secretName: js-aws-iam-example # name of the AWSIAMRole resource
---
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: js-aws-iam-example
spec:
  roleReference: aws-iam-example
